fragment PageParts on Page {
  title
  description
  blocks {
    __typename
    ... on PageBlocksHero {
      otsikko
      sisalto
      bgImg
    }
    ... on PageBlocksKuva {
      img
    }
    ... on PageBlocksPalsta {
      palsta_otsikko
      palsta_sisalto
      linkit {
        __typename
        url
        title
      }
    }
  }
}

fragment GlobalParts on Global {
  mainnav {
    __typename
    nav {
      __typename
      href
      label
    }
  }
}
