fragment PageParts on Page {
  title
  description
  blocks {
    __typename
    ... on PageBlocksHero {
      otsikko
      sisalto
      bgImg
      kuvateksti
    }
    ... on PageBlocksKuva {
      img
      kuva_kuvateksti
    }
    ... on PageBlocksPalsta {
      palsta_kuva
      palsta_kuvateksti
      palsta_reverse
      palsta_otsikko
      palsta_sisalto
      palsta_linkit {
        __typename
        url
        title
      }
    }
    ... on PageBlocksKokemus {
      kokemus_otsikko
      kokemus_sisalto
      kokemus_lista {
        __typename
        title
        ajankohta
        kuvaus
      }
    }
  }
}

fragment SettingsParts on Settings {
  title
  sivuston_nimi
  instagram_url
  linkedin_url
  mainnav {
    __typename
    nav {
      __typename
      url
      title
    }
  }
}
