fragment PageParts on Page {
  title
  description
  blocks {
    __typename
    ... on PageBlocksHero {
      otsikko
      sisalto
      bgImg
      kuvateksti
    }
    ... on PageBlocksKuva {
      img
      kuva_kuvateksti
    }
    ... on PageBlocksPalsta {
      palsta_kuva
      palsta_kuvateksti
      palsta_reverse
      palsta_otsikko
      palsta_sisalto
      palsta_linkit {
        __typename
        url
        title
      }
    }
  }
}

fragment GlobalParts on Global {
  mainnav {
    __typename
    nav {
      __typename
      href
      label
    }
  }
}
